title: Abhinav Nehra
logo: /img/p1.jpg
description: I'm a Data Science Grad Student at Univeristy at Buffalo with 3.5+ years of industry experience in Cloud Infrastructure and Data Engineering domain and I'm passionate about the Data Science and Engineering field and their application in generating valuable insights from messy and large datasets. Imagine a puzzle — I love piecing together information from chaotic datasets to reveal the big picture and unlock valuable secrets within!
theme: jekyll-theme-minimal
